language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false
before_install: composer self-update
install: composer install --dev

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  email: false
  slack:
    secure: AFFqq2tPtXyzmiSiULuIH5gelCL94mLxiYSsHVhaw1UTqjg/rhHvIkitw3mXfdW8CX0VbqJ4FFzAxx89bzGavWL4AUcmbF6WZCj3FSRhuvzMU66x0w8koczo00Wlya2cyQ6IIWgDO+L7VVj2SFQw48/EEDO4G+Ip9AxpR55wguE=
